// Generated by CoffeeScript 1.3.1
(function() {
  var game, renderer, socket;

  game = new Game();

  renderer = new Renderer(game);

  setInterval(function() {
    return renderer.draw();
  }, 40);

  socket = io.connect('http://localhost:8080');

  socket.on('connect', function() {
    return socket.emit('playerJoin', null);
  });

  socket.on('load game', function(data) {
    console.log(data);
    return game.load(data);
  });

  socket.on('cycle', function(data) {
    return console.log(data);
  });

  socket.on('new piece', function(data) {
    game.board[data['row']][data['col']] = data['piece'];
    return console.log(data);
  });

}).call(this);
