// Generated by CoffeeScript 1.3.1
(function() {
  var socket;

  socket = io.connect('http://localhost:8080');

  socket.on('cycle', function(data) {
    return console.log(data);
  });

}).call(this);
