// Generated by CoffeeScript 1.3.1
(function() {
  var Renderer;

  Renderer = (function() {

    Renderer.name = 'Renderer';

    Renderer.prototype.game = null;

    Renderer.prototype.canvas = null;

    function Renderer(game) {
      this.game = game;
      this.canvas = document.getElementById('canvas').getContext('2d');
    }

    Renderer.prototype.draw = function() {
      var col, img, row, _i, _ref, _results;
      img = new Image();
      img.src = 'client/images/hexagon.png';
      this.canvas.clearRect(0, 0, 960, 540);
      this.canvas.fillStyle = "#000";
      this.canvas.strokeStyle = "#000";
      _results = [];
      for (row = _i = 0, _ref = this.game.board.length - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; row = 0 <= _ref ? ++_i : --_i) {
        _results.push((function() {
          var _j, _ref1, _results1;
          _results1 = [];
          for (col = _j = 0, _ref1 = this.game.board[row].length - 1; 0 <= _ref1 ? _j <= _ref1 : _j >= _ref1; col = 0 <= _ref1 ? ++_j : --_j) {
            if ((row % 2 === 0 && col % 2 === 0) || (row % 2 === 1 && col % 2 === 1)) {
              this.canvas.drawImage(img, 0, 0, 200, 200, 36 * col, row * 21, 45, 45);
              if (this.game.board[row][col] !== 0) {
                _results1.push(this.canvas.fillRect(36 * col, row * 21, 20, 20));
              } else {
                _results1.push(void 0);
              }
            } else {
              _results1.push(void 0);
            }
          }
          return _results1;
        }).call(this));
      }
      return _results;
    };

    return Renderer;

  })();

  window.Renderer = Renderer;

}).call(this);
