// Generated by CoffeeScript 1.3.1
(function() {
  var canvas, draw;

  canvas = document.getElementById('canvas').getContext('2d');

  draw = function() {
    var col, img, row, _i, _results;
    img = new Image();
    img.src = 'client/images/hexagon.png';
    canvas.clearRect(0, 0, 960, 540);
    canvas.fillStyle = "#000";
    canvas.strokeStyle = "#000";
    _results = [];
    for (row = _i = 0; _i <= 36; row = ++_i) {
      _results.push((function() {
        var _j, _results1;
        _results1 = [];
        for (col = _j = 0; _j <= 36; col = ++_j) {
          if ((row % 2 === 0 && col % 2 === 0) || (row % 2 === 1 && col % 2 === 1)) {
            _results1.push(canvas.drawImage(img, 0, 0, 200, 200, 36 * col, row * 21, 45, 45));
          } else {
            _results1.push(void 0);
          }
        }
        return _results1;
      })());
    }
    return _results;
  };

  setInterval(draw, 40);

}).call(this);
