// Generated by CoffeeScript 1.3.1
(function() {
  var route;

  route = function(pathname) {
    return console.log("About to route a request for " + pathname);
  };

  exports.route = route;

}).call(this);
