// Generated by CoffeeScript 1.3.1
(function() {
  var http, start, url;

  http = require("http");

  url = require("url");

  start = function(route) {
    var onRequest;
    onRequest = function(request, response) {
      var pathname;
      pathname = url.parse(request.url).pathname;
      console.log("Request for " + pathname + " received.");
      route(pathname);
      response.writeHead(200, {
        "Content-Type": "text/plain"
      });
      response.write("Hello World");
      return response.end();
    };
    http.createServer(onRequest).listen(8888);
    return console.log("Server has started.");
  };

  exports.start = start;

}).call(this);
