// Generated by CoffeeScript 1.3.1
(function() {
  var Archer, Game, Mage, Spearman, Swordsman, Unit, game, io, playerCount;

  Game = require('../common/game.js').Game;

  Unit = require('../models/unit.js').Unit;

  Mage = require('../models/mage.js').Mage;

  Archer = require('../models/archer.js').Archer;

  Swordsman = require('../models/swordsman.js').Swordsman;

  Spearman = require('../models/spearman.js').Spearman;

  io = require('socket.io').listen(8080);

  playerCount = 0;

  game = new Game();

  io.sockets.on('connection', function(socket) {
    setInterval(function() {
      socket.emit('cycle', {
        "players": playerCount
      });
      return console.log(game);
    }, 2000);
    socket.on('playerJoin', function(socket) {
      var test;
      playerCount++;
      console.log('player join');
      return test = new Mage(0);
    });
    return socket.on('disconnect', function(socket) {
      playerCount--;
      return console.log('player left');
    });
  });

}).call(this);
