// Generated by CoffeeScript 1.3.1
(function() {
  var Archer, Game, Mage, Spearman, Swordsman, Unit, game, io;

  Game = require('../common/game.js').Game;

  Unit = require('../models/unit.js').Unit;

  Mage = require('../models/mage.js').Mage;

  Archer = require('../models/archer.js').Archer;

  Swordsman = require('../models/swordsman.js').Swordsman;

  Spearman = require('../models/spearman.js').Spearman;

  io = require('socket.io').listen(8080);

  game = new Game();

  io.sockets.on('connection', function(socket) {
    socket.emit('load game', game.save());
    setInterval(function() {
      return socket.emit('cycle', {
        "players": game.getPlayerCount()
      });
    }, 2000);
    socket.on('playerJoin', function(socket) {
      var test;
      game.playerJoin();
      console.log('player join');
      test = new Mage(0);
      if (game.board[4][4] === 0) {
        game.board[4][4] = test;
        return io.sockets.emit('new piece', {
          "row": 4,
          "col": 4,
          "piece": test
        });
      } else {
        game.board[8][8] = test;
        return io.sockets.emit('new piece', {
          "row": 8,
          "col": 8,
          "piece": test
        });
      }
    });
    return socket.on('disconnect', function(socket) {
      game.playerLeave();
      return console.log('player left');
    });
  });

}).call(this);
