// Generated by CoffeeScript 1.3.1
(function() {
  var ArcherFactory,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; };

  ArcherFactory = (function(_super) {

    __extends(ArcherFactory, _super);

    ArcherFactory.name = 'ArcherFactory';

    function ArcherFactory(o) {
      ArcherFactory.__super__.constructor.call(this, "Archer Factory", 100, 10, 10, o);
    }

    return ArcherFactory;

  })(Factory);

  window.ArcherFactory = ArcherFactory;

}).call(this);
