// Generated by CoffeeScript 1.3.1
(function() {
  var Factory;

  Factory = (function() {

    Factory.name = 'Factory';

    function Factory(name, l, st, bcd) {
      this.name = name;
      this.life = l;
      this.spawn_time = st;
      this.build_cooldown = bcd;
    }

    Factory.prototype.life = 0;

    Factory.prototype.spawn_time = 0;

    Factory.prototype.build_cooldown = 0;

    return Factory;

  })();

}).call(this);
