// Generated by CoffeeScript 1.3.1
(function() {
  var Mage,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; };

  Mage = (function(_super) {

    __extends(Mage, _super);

    Mage.name = 'Mage';

    function Mage() {
      Mage.__super__.constructor.call(this, "Mage", 100, 10, 10, 10);
    }

    return Mage;

  })(Unit);

}).call(this);
