// Generated by CoffeeScript 1.3.1
(function() {
  var MageFactory,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; };

  MageFactory = (function(_super) {

    __extends(MageFactory, _super);

    MageFactory.name = 'MageFactory';

    function MageFactory() {
      MageFactory.__super__.constructor.call(this, "Mage Factory", 100, 10);
    }

    return MageFactory;

  })(Factory);

}).call(this);
