// Generated by CoffeeScript 1.3.1
(function() {
  var Spearman,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; };

  Spearman = (function(_super) {

    __extends(Spearman, _super);

    Spearman.name = 'Spearman';

    function Spearman(o) {
      Spearman.__super__.constructor.call(this, "Spearman", 100, 10, 10, 10, 10, o);
    }

    return Spearman;

  })(Unit);

  if (typeof global === "undefined") {
    window.Spearman = Spearman;
  } else {
    exports.Spearman = Spearman;
  }

}).call(this);
