// Generated by CoffeeScript 1.3.1
(function() {
  var Swordsman,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; };

  Swordsman = (function(_super) {

    __extends(Swordsman, _super);

    Swordsman.name = 'Swordsman';

    function Swordsman(o) {
      Swordsman.__super__.constructor.call(this, "Swordsman", 100, 10, 10, 10, 10, o);
    }

    return Swordsman;

  })(Unit);

  if (typeof global === "undefined") {
    window.Swordsman = Swordsman;
  } else {
    exports.Swordsman = Swordsman;
  }

}).call(this);
